### ISSUE TITLE
Cannot pip install on M2 Ventura

### ISSUE THREAD

**Issue by Pizzanomicon** [sanguinariojoe/pip-openexr#13]
pip install OpenEXR

yields:

Collecting OpenEXR
  Using cached OpenEXR-1.3.9.tar.gz (13 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: OpenEXR
  Building wheel for OpenEXR (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Looking for libOpenEXR...
      OpenEXR.cpp:36:10: fatal error: 'ImfIO.h' file not found
      #include <ImfIO.h>
               ^~~~~~~~~
      1 error generated.
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for OpenEXR
  Running setup.py clean for OpenEXR
Failed to build OpenEXR
Installing collected packages: OpenEXR
  Running setup.py install for OpenEXR ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for OpenEXR did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Looking for libOpenEXR...
      /Users/philw/miniconda3/envs/dev1/lib/python3.10/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      OpenEXR.cpp:36:10: fatal error: 'ImfIO.h' file not found
      #include <ImfIO.h>
               ^~~~~~~~~
      1 error generated.
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> OpenEXR

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

**Comment by duklin** [comment]
I tried to modify the setup.py file based on this comment: https://github.com/jamesbowman/openexrpython/issues/44#issuecomment-1305799651

The command `pip install -e .` finished successfully. However, when I try to import it, it shows the following error:
```
python -c "import OpenEXR"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: dlopen(/Users/duklin/xrite/pip-openexr/OpenEXR.cpython-39-darwin.so, 0x0002): symbol not found in flat namespace '__ZN7Iex_2_57TypeExcD1Ev'
```

Then I continued reading the issue and successfully installed it with the help of the next comment: https://github.com/jamesbowman/openexrpython/issues/44#issuecomment-1510146744

**Comment by duklin** [comment]
please try to install it from here https://github.com/sanguinariojoe/pip-openexr/pull/22

**Comment by sanguinariojoe** [comment]
I made and uploaded autobuilds for all platforms. just do `pip install OpenEXR==1.3.9` and the problem shall be automagically fixed
