### ISSUE TITLE
Error when using windows system

### ISSUE THREAD

**Issue by hlu2021** [sanguinariojoe/pip-openexr#15]
Hi,
Does this binder works with windows system? I use pip install and it kept give me error message below when I use it in the windows system even if I built OPENEXR in C successfully.

(base) C:\Users\Hui\Documents\GitHub>pip install ./pip-openexr
Processing c:\users\hui\documents\github\pip-openexr
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: OpenEXR
  Building wheel for OpenEXR (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [5 lines of output]
      Looking for libOpenEXR...
      cl : Command line warning D9002 : ignoring unknown option '-g'
      OpenEXR.cpp
      OpenEXR.cpp(36): fatal error C1083: Cannot open include file: 'ImfIO.h': No such file or directory
      error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.35.32215\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for OpenEXR
  Running setup.py clean for OpenEXR
Failed to build OpenEXR
Installing collected packages: OpenEXR
  Running setup.py install for OpenEXR ... error
  error: subprocess-exited-with-error

  × Running setup.py install for OpenEXR did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      Looking for libOpenEXR...
      C:\Users\Hui\anaconda3\lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      cl : Command line warning D9002 : ignoring unknown option '-g'
      OpenEXR.cpp
      OpenEXR.cpp(36): fatal error C1083: Cannot open include file: 'ImfIO.h': No such file or directory
      error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.35.32215\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2

**Comment by sanguinariojoe** [comment]
On Windows things are slightly more complex. First you need to create an env variable INCLUDE telling the compiler where the .h files of openexr can be found.

See https://learn.microsoft.com/en-us/cpp/preprocessor/hash-include-directive-c-cpp?view=msvc-170

You also need to add the folders where the .lib files are to LD_LIBRARY_PATH env variable.

Finally the .dll folders shall be added to PATH env variable

**Comment by hlu2021** [comment]
Hi Sanguinariojoe,
Thank you for your reply. I configured the Include, LD_LIBRARY_PATH env variable and PATH env variable. But the error message still shows the same. Do you have any recommendations what I should try to fix the problem? Thanks.

**Comment by sanguinariojoe** [comment]
I suppose I have to build a github action to autobuild binaries...

Meanwhile, can you open a terminal (cmd) and type

`dir %INCLUDE%`

It should list several .h files. Among them it must be listed the  ImfIO.h file. Otherwise you set the wrong folder on the INCLUDE env var

**Comment by Kaitology** [comment]
Hi Joe,

I also built OpenEXR 3.1.7 on Windows. Missing a bunch of files - lucky I have another build of OpenEXR in my Houdini folder. Managed to get much further in the install process but still missing "Iex.lib" that's preventing me from finishing the install. 

Are there any recommended versions? I'm on Python 3.9

**Comment by sanguinariojoe** [comment]
Guys, I made and uploaded autobuilds for all platforms. just do `pip install OpenEXR==1.3.9` and the problem shall be automagically fixed
