### ISSUE TITLE
import time crash

### ISSUE THREAD

**Issue by arpit15** [sanguinariojoe/pip-openexr#17]
I am getting the following error when I try to import the package.
I downloaded the repo and `pip install -e .` to install the package.

```
ImportError: /home/arpit/projects/pip-openexr/OpenEXR.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZTIN7Imf_3_114TypedAttributeIN9Imath_2_44Vec2IfEEEE
```

**Comment by sanguinariojoe** [comment]
It seems you are missing the openexr libraries on the LD_LIBRARY_PATH (the set of paths where the system look for the libraries)

**Comment by sanguinariojoe** [comment]
I made and uploaded autobuilds for all platforms. just do `pip install OpenEXR==1.3.9` and the problem shall be automagically fixed
