### ISSUE TITLE
Error occur while pip install openEXR

### ISSUE THREAD

**Issue by G-raghava** [sanguinariojoe/pip-openexr#18]
Collecting openEXR
  Using cached OpenEXR-1.3.9.tar.gz (13 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: openEXR
  Building wheel for openEXR (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      Looking for libOpenEXR...
      cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
      OpenEXR.cpp:36:10: fatal error: ImfIO.h: No such file or directory
       #include <ImfIO.h>
                ^~~~~~~~~
      compilation terminated.
      error: command '/usr/bin/gcc' failed with exit code 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for openEXR
  Running setup.py clean for openEXR
Failed to build openEXR
ERROR: Could not build wheels for openEXR, which is required to install pyproject.toml-based projects

How to resolve the issue.

**Comment by sanguinariojoe** [comment]
I made and uploaded autobuilds for all platforms. just do pip install OpenEXR==1.3.9 and the problem shall be automagically fixed

**Comment by den-run-ai** [comment]
I think libopenexr-dev is required on the system? @sanguinariojoe

**Comment by den-run-ai** [comment]
i just installed with conda:

https://anaconda.org/conda-forge/openexr

**Comment by sanguinariojoe** [comment]
> I think libopenexr-dev is required on the system? @sanguinariojoe

Nope, OpenEXR is statically linked on the autobuilds

**Comment by sanguinariojoe** [comment]
I am closing this. Feel free to open a new issue if you find further problems
