### ISSUE TITLE
PyPi using 1.3.9 but latest release on official repository is 1.3.7?

### ISSUE THREAD

**Issue by ecpwll** [sanguinariojoe/pip-openexr#19]
It seems like PyPi's latest OpenEXR version is 1.3.9 but the latest release on the official repository is 1.3.7?  I do not see 1.3.9 referenced anywhere outside PyPi.  How is that possible?

Installing 1.3.9 I am getting an import error, seemingly because of a version mismatch.  However 1.3.7 will not install via pip, I get numerous errors including a "legacy-install-failure".  How can I fix?

Building on an M1 Max Macbook Pro

**Comment by sanguinariojoe** [comment]
The version of the Pypi package and the OpenEXR are unlinked, mainly because Pypi enforces to.

I made and uploaded autobuilds for all platforms. just do `pip install OpenEXR==1.3.9` and the problem shall be auotmagically fixed
