### ISSUE TITLE
writePixels is slow when compared to other libraries

### ISSUE THREAD

**Issue by TobiasNoell** [sanguinariojoe/pip-openexr#25]
I had used [imageio](https://github.com/imageio/imageio) (with FreeImage backend) to store EXR images and now switched to `pip-openexr` (1.3.8) because I also need to parse header data.

I noticed a significant worse performance when writing images, e.g. for a 3620 × 3620 pixels RGB image
- imageio would take 0.6 seconds to store to disk
- while `pip-openexr` would take 2.33 seconds (almost 4x time) for the same file / operation

The majority of the time (> 98%) of the serialization code is being spent in the `writePixels` function.

Is there any way to make the serialization quicker?

**Comment by sanguinariojoe** [comment]
I can take a look on the OpenEXR library to check if they are considering alternative/faster ways to write files. But that `writePixels()` function belongs to the [OpenEXR](https://github.com/AcademySoftwareFoundation/openexr) library, and thus they are the ones to ask for performance improvements.

**Comment by TobiasNoell** [comment]
One interesting aspect is that FreeImage is also using OpenEXR itself https://github.com/dllsystem/FreeImage/blob/master/Source/FreeImage/PluginEXR.cpp

So, it might be that the issue is rather in the glue code (the Python writePixels executes a buch of other stuff before handing over to OpenEXRs writePixels) 🤔

**Comment by sanguinariojoe** [comment]
Ah OK, for some reason I though you were meaning the inner `writePixels()`. OK, I will check what is going on (not this week).

Feel free to ping me if you feel I take too long

**Comment by TobiasNoell** [comment]
Thanks for you effort and for maintaining this module :)

**Comment by TobiasNoell** [comment]
Can be closed, turned out there were just different default compression settings for the different libraries (ZIP vs PIZ).
