### ISSUE TITLE
cannot import on windows

### ISSUE THREAD

**Issue by MarcBresson** [sanguinariojoe/pip-openexr#27]
Hello,

I am using python 3.11 on Windows 11 and I cannot import OpenEXR. When I try, i get this error:

```python
>>> import OpenEXR
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: DLL load failed while importing OpenEXR: The specified module could not be found.
```

**Comment by sanguinariojoe** [comment]
How did you installed it?

**Comment by MarcBresson** [comment]
I compiled the openEXR library myself with cmake on windows.
I cloned this repo and ran 'pip install .'

**Comment by sanguinariojoe** [comment]
The error seems to say that the openexr you compiled with cmake cannot be found. It should be available somewhere on your path, or you can use [os.add_dll_directory()](https://docs.python.org/3/library/os.html#os.add_dll_directory) before importing

**Comment by MarcBresson** [comment]
Windows does not search dll in PATH items. So the only way to make it work as you mentioned is using the os method.

So that doesn't work, even if `C:\Program Files (x86)\OpenEXR\bin` is on the PATH:
```bash
>>> import OpenEXR
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: DLL load failed while importing OpenEXR: The specified module could not be found.
```

but that works:

```bash
>>> import os
>>> os.add_dll_directory(r"C:\Program Files (x86)\OpenEXR\bin")
<AddedDllDirectory('C:\\Program Files (x86)\\OpenEXR\\bin')>
>>> import OpenEXR
>>>
```

Thanks a lot for your help.
