### ISSUE TITLE
Cannot Build on MacOSX 10.15.7

### ISSUE THREAD

**Issue by erichorwitz** [sanguinariojoe/pip-openexr#4]
$ python3.9 setup.py build

Looking for libOpenEXR...
running build
running build_py
creating build
creating build/lib.macosx-10.9-x86_64-3.9
copying Imath.py -> build/lib.macosx-10.9-x86_64-3.9
running build_ext
building 'OpenEXR' extension
creating build/temp.macosx-10.9-x86_64-3.9
gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch x86_64 -g -I/usr/include/OpenEXR -I/usr/local/include/OpenEXR -I/opt/local/include/OpenEXR -I/usr/include/Imath -I/usr/local/include/Imath -I/opt/local/include/Imath -I/Library/Frameworks/Python.framework/Versions/3.9/include/python3.9 -c OpenEXR.cpp -o build/temp.macosx-10.9-x86_64-3.9/OpenEXR.o -g -DVERSION="1.3.8" -std=c++11 -Wc++11-extensions -Wc++11-long-long
In file included from OpenEXR.cpp:40:
In file included from /usr/local/include/OpenEXR/ImfBoxAttribute.h:21:
In file included from /usr/local/include/OpenEXR/ImathBox.h:65:
In file included from /usr/local/include/OpenEXR/ImathVec.h:46:
In file included from /usr/local/include/OpenEXR/ImathExc.h:46:
In file included from /usr/local/include/OpenEXR/ImathNamespace.h:78:
/usr/local/include/OpenEXR/IlmBaseConfig.h:32:9: warning: 'IEX_INTERNAL_NAMESPACE' macro redefined [-Wmacro-redefined]
#define IEX_INTERNAL_NAMESPACE Iex_2_5
        ^
/usr/local/include/OpenEXR/IexConfig.h:19:9: note: previous definition is here
#define IEX_INTERNAL_NAMESPACE Iex_3_1
        ^
OpenEXR.cpp:118:21: error: virtual function 'tellg' has a different return type ('Imath_2_5::Int64' (aka 'unsigned long')) than the function it
      overrides (which has return type 'uint64_t' (aka 'unsigned long long'))
    virtual Int64   tellg ();
            ~~~~~   ^
/usr/local/include/OpenEXR/ImfIO.h:82:22: note: overridden virtual function is here
    virtual uint64_t    tellg () = 0;
            ~~~~~~~~    ^
OpenEXR.cpp:119:21: warning: 'C_IStream::seekg' hides overloaded virtual function [-Woverloaded-virtual]
    virtual void    seekg (Int64 pos);
                    ^
/usr/local/include/OpenEXR/ImfIO.h:90:18: note: hidden overloaded virtual function 'Imf_3_1::IStream::seekg' declared here: type mismatch at 1st
      parameter ('uint64_t' (aka 'unsigned long long') vs 'Imath_2_5::Int64' (aka 'unsigned long'))
    virtual void        seekg (uint64_t pos) = 0;
                        ^
OpenEXR.cpp:183:21: error: virtual function 'tellp' has a different return type ('Imath_2_5::Int64' (aka 'unsigned long')) than the function it
      overrides (which has return type 'uint64_t' (aka 'unsigned long long'))
    virtual Int64   tellp ();
            ~~~~~   ^
/usr/local/include/OpenEXR/ImfIO.h:154:22: note: overridden virtual function is here
    virtual uint64_t    tellp () = 0;
            ~~~~~~~~    ^
OpenEXR.cpp:184:21: warning: 'C_OStream::seekp' hides overloaded virtual function [-Woverloaded-virtual]
    virtual void    seekp (Int64 pos);
                    ^
/usr/local/include/OpenEXR/ImfIO.h:162:18: note: hidden overloaded virtual function 'Imf_3_1::OStream::seekp' declared here: type mismatch at 1st
      parameter ('uint64_t' (aka 'unsigned long long') vs 'Imath_2_5::Int64' (aka 'unsigned long'))
    virtual void        seekp (uint64_t pos) = 0;
                        ^
OpenEXR.cpp:746:33: error: allocating an object of abstract class type 'C_IStream'
          object->istream = new C_IStream(fo);
                                ^
/usr/local/include/OpenEXR/ImfIO.h:90:18: note: unimplemented pure virtual method 'seekg' in 'C_IStream'
    virtual void        seekg (uint64_t pos) = 0;
                        ^
OpenEXR.cpp:995:33: error: allocating an object of abstract class type 'C_OStream'
          object->ostream = new C_OStream(fo);
                                ^
/usr/local/include/OpenEXR/ImfIO.h:162:18: note: unimplemented pure virtual method 'seekp' in 'C_OStream'
    virtual void        seekp (uint64_t pos) = 0;
                        ^
3 warnings and 4 errors generated.
error: command '/usr/bin/gcc' failed with exit code 1

**Comment by erichorwitz** [comment]
$ gcc -v

Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/c++/4.2.1
Apple clang version 12.0.0 (clang-1200.0.32.29)
Target: x86_64-apple-darwin19.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

**Comment by sanguinariojoe** [comment]
Hey!

For family related reasons i cannot handle this now. I'll try to get back ASAP

**Comment by sanguinariojoe** [comment]
Hey!

Can you check what happens if you add `#include<Imath/ImathConfig.h>` at the beginning of OpenEXR.cpp?

**Comment by xav-ie** [comment]
Also I have no idea if this will help but try building lmath and openexr yourself if you installed them through brew. Also see https://github.com/jamesbowman/openexrpython/issues/44#issuecomment-1231008327 for more details on what I did to get it to work.

**Comment by duklin** [comment]
please try to install it from here https://github.com/sanguinariojoe/pip-openexr/pull/22

**Comment by sanguinariojoe** [comment]
I made and uploaded autobuilds for all platforms. just do `pip install OpenEXR==1.3.9` and the problem shall be automagically fixed
