### ISSUE TITLE
Building on macOS 12.5.1 Monterey

### ISSUE THREAD

**Issue by nedwilson** [sanguinariojoe/pip-openexr#9]
Thought I'd share the steps I took to get this to build on macOS Monterey. Homebrew has updated Python to 3.10 as of this writing ( September 1, 2022 ) but I needed to build OpenEXR for Python 3.9. This is further complicated by the fact that Homebrew is now using the OpenEXR v3 libraries as a default, but OpenEXR-Python uses the OpenEXR v2 libraries.
1. Downgrade homebrew as much as possible
* brew uninstall --ignore-dependencies python@3.10
* brew install python@3.9
* brew uninstall --ignore-dependencies openexr
* brew install openexr@2
* brew uninstall --ignore-dependencies boost-python3
* brew uninstall imath
2. Install version of boost-python3 using a raw commit
* cd /tmp
* wget https://raw.githubusercontent.com/Homebrew/homebrew-core/f68dc0e31506f302409b736bc1dd1ef3e106f75a/Formula/boost-python3.rb
* brew install ./boost-python3.rb
3. Build and install OpenEXR 2 from source
* wget https://github.com/AcademySoftwareFoundation/openexr/archive/refs/tags/v2.5.8.zip -O openexr-2.5.8.zip
* unzip openexr-2.5.8.zip
* cd openexr-2.5.8
* mkdir build
* cd build
* cmake -DPyIlmBase_Python3_SITEARCH_REL=/usr/local/lib/python3.9/site-packages ..
* make
* make install
4. Use git to clone this project
* cd /tmp
* git clone https://github.com/sanguinariojoe/pip-openexr
* cd pip-openexr
5. Edit the setup.py file for this project. Remove the logic that checks for platform.system() == "Linux" and assigns libraries. Replace with libraries=['Iex', 'Half', 'Imath', 'IlmImf', 'z']
6. Build and install this project
* /usr/local/bin/python3.9 ./setup.py build
* /usr/local/bin/python3.9 ./setup.py install 
7. Test it
* /usr/local/bin/python3.9
* import OpenEXR

**Comment by duklin** [comment]
please try to install it from here https://github.com/sanguinariojoe/pip-openexr/pull/22

**Comment by sanguinariojoe** [comment]
I made and uploaded autobuilds for all platforms. just do `pip install OpenEXR==1.3.9` and the problem shall be automagically fixed
